spring:
  datasource:
      url: jdbc:mysql://localhost:3306/dbtest1
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        enable: true
        aop-patterns: com.hypnos.springboot3webadmin.*  #springbean监控
        filters: stat,wall,slf4j  #所有开启的功能

        stat-view-servlet: #监控页配置
          enabled: false
          login-username: admin
          login-password: admin
          resetEnable: false

        web-stat-filter: #web监控
          enabled: true
          urlPattern: /*
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

        filter:
          stat: #sql监控
            slow-sql-millis: 1000
            logSlowSql: true
            enabled: true
          wall: #防火墙
            enabled: true
            config:
              drop-table-allow: false
  data:
    redis:
      url: redis://yuanrui:A2w3d45v6h7u8@r-wz987skvkrzrdgf2q6pd.redis.rds.aliyuncs.com:6379

debug: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # 指定扫描xml文件路径
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  endpoints:
    enabled-by-default: true # 默认开启所有监控断点
    web:
      exposure:
        include: '*' # 以Web的方式暴露所有端点
